version: "3.7"
services:
  product-service:
    build: ./product-service
    restart: always
    ports:
      - 8082:8082
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/product-service-db
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: product-service-db
      MYSQL_USER: product-service
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
