eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-server:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventories/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
